- package.json
- public/views/inviteCorrespondentDevice.html
- public/views/walletHome.html
- src/js/controllers/walletHome.js
> fix for package name

- public/views/preferences.html
- public/views/preferencesGlobal.html
- src/css/main.css
> Long name of wallet does not fit

- src/css/main.css
> removed scroll from transaction table

- .eslintrc
- Gruntfile.js
- angular-bitcore-wallet-client/bitcore-wallet-client/lib/api.js
- package.json
- public/index.html
- src/js/controllers/authConfirmation.js
- src/js/controllers/copayers.js
- src/js/controllers/correspondentDevice.js
- src/js/controllers/index.js
- src/js/controllers/inviteCorrespondentDevice.js
- src/js/controllers/preferencesDelete.js
- src/js/controllers/preferencesInformation.js
- src/js/controllers/preferencesLogs.js
- src/js/controllers/recoveryFromSeed.js
- src/js/controllers/walletHome.js
- src/js/directives/qrScanner.js
- src/js/init.js
- src/js/live-reload.js
- src/js/services/confirmDialog.js
- src/js/services/correspondentListService.js
- src/js/services/fileSystem.js
- src/js/services/go.js
- src/js/services/profileService.js
- src/js/services/txFormatService.js
- util/version.js
> #25 Live-Reload

- src/js/services/profileService.js
> Not able to send amount with 6 digits after comma #38

- src/js/services/profileService.js
> Not able to send amount with 6 digits after comma

- angular-bitcore-wallet-client/bitcore-wallet-client/lib/api.js
- public/views/walletHome.html
- src/css/main.css
- src/js/controllers/authConfirmation.js
- src/js/controllers/copayers.js
- src/js/controllers/correspondentDevice.js
- src/js/controllers/index.js
- src/js/controllers/inviteCorrespondentDevice.js
- src/js/controllers/preferencesDelete.js
- src/js/controllers/preferencesInformation.js
- src/js/controllers/preferencesLogs.js
- src/js/controllers/recoveryFromSeed.js
- src/js/controllers/walletHome.js
- src/js/directives/qrScanner.js
- src/js/init.js
- src/js/services/confirmDialog.js
- src/js/services/correspondentListService.js
- src/js/services/fileSystem.js
- src/js/services/go.js
- src/js/services/profileService.js
- src/js/services/txFormatService.js
1. Changed **HTML**-structure
2. Applied CSS styles
3. **getFontSizeForWalletNumber** function inside _walletHome.js_
> #15 dynamic styles for amount

- public/views/preferencesGlobal.html
fixes #23 
removed balance from global settings since we are already showing it in wallet settings.
> #23 byte balance issue

- src/css/main.css
> Issue 52: Error message text does not fit

- angular-bitcore-wallet-client/bitcore-wallet-client/lib/log.js
- src/js/services/go.js
- src/js/services/logHeader.js
> fix for wrong qr-code 

- src/js/controllers/walletHome.js
> change explorer address from http to https 

- public/views/walletHome.html
1) Added "scrollable" class to the tab view
> Make Send tab scrollable

- src/css/main.scss
- src/js/directives/scrollable.directive.js
- src/js/live-reload.js
Fixes #67
1) Used "scrollable" class to create a directive
2) Assign event to track onscroll event
3) Change background depending on a scroll position
> Top-Bar has transparent background

- public/views/walletHome.html
> #84 resolved: Validation for send amount allow negative numbers

- public/views/walletHome.html
- src/css/main.scss
> Issue 85: gap between transaction list and show history button is big 

- src/js/directives/validAddress.directive.js
> Issue 106: Dagcoin app fails o the first start

- cordova/build.sh
- cordova/config.xml
- package.json
> android package error fix

- public/views/preferencesAdvanced.html
closes #102 
commented out sweep menu in advances menu
> hide Sweep paper wallet from settings

- src/js/services/configService.js
> fixed bug with changing wallet name

- src/js/controllers/export.js
> backup name fix

- src/js/controllers/walletHome.js
> fix for undefined error message

- .stylelintrc
- Gruntfile.js
- package.json
- src/css/main.scss
- src/css/mobile.scss
- src/css/variables.scss
- src/js/routes.js
closes #78 
1) Grunt modules (**stylelint**, **postcss**)
2) **Scss** pluging for stylelint
3) .**stylelintrc** config file
4) Apply **autoprifixer** (last 4 version of each browser)
5) **Fixing** stylelint **errors**
> Stylelint for scss

- public/views/copayers.html
- public/views/includes/sidebar.html
- public/views/preferencesAdvanced.html
- src/js/controllers/copayers.js
- src/js/controllers/create.js
- src/js/controllers/index.js
- src/js/controllers/sidebar.js
- src/js/routes.js
> Issue-160: Reactivate shared wallet functionality

- Gruntfile.js
- public/views/includes/menu.html
- public/views/includes/sidebar.html
- public/views/includes/versionAndWalletType.html
- src/css/main.scss
- src/css/mobile.scss
- src/css/variables.scss
- src/js/controllers/sidebar.js
- src/js/routes.js
1) Wallet preferences opening separately for each wallet
2) New sidebar design
3) New bottom bar design
4) New buttons design
5) New inputs design
> UI changes

- Gruntfile.js
- public/views/includes/menu.html
- public/views/includes/sidebar.html
- public/views/includes/versionAndWalletType.html
- src/css/main.scss
- src/css/mobile.scss
- src/css/variables.scss
- src/js/controllers/sidebar.js
- src/js/routes.js
> Revert "UI changes"

- src/js/controllers/index.js
- src/js/services/discoveryService.js
- src/js/services/fundingNodeService.js
closes #180 
closes #178 
closes #176
> funding-node-service: refactoring service and fix a multiple rewrite for settings

- src/js/controllers/splash.js
- src/js/services/fileSystem.js
- src/js/services/fundingNodeService.js
> Issue-187: getAppDataDir is not a function

- src/js/services/chooseFeeTypeService.js
- src/js/services/fileSystem.js
- src/js/services/fundingNodeService.js
fix startup application with full wallet
fix file system logic
fix cordova path
> choose fee type service refactoring

- package.json
- public/views/import.html
- public/views/includes/password.html
> #175 Password is prefilled

- Gruntfile.js
Closes #200 
* fixed uglify
* removed unused command from grunt
* added babel transpiler to browserify task
> uglify fix

- public/views/create.html
- public/views/import.html
- public/views/preferencesDeviceName.html
- public/views/preferencesGlobal.html
- src/css/main.scss
closes #202 
1) "Language" setting is hidden
2) Add [disabled] state to the buttons
3) Replace all existing buttons with appropriate alternatives
> Remove blue from the UI triggers

- src/css/main.scss
> #185 Scroll disappears from send page

- .gitignore
- public/views/preferencesGlobal.html
- src/js/controllers/preferencesGlobal.js
1) Rename back-up setting links for a light wallet
2) Hide full back-up option for a light wallet
> Light wallet back-up settings

- public/views/preferencesGlobal.html
- src/js/controllers/index.js
- src/js/controllers/preferencesGlobal.js
- src/js/controllers/splash.js
- src/js/services/changeWalletTypeService.js
- src/js/services/localStorage.js
> [WIP]Issue 193 - feature: change wallet type - first solution

- public/views/walletHome.html
- src/css/main.scss
- src/js/controllers/index.js
1) Adjust **styling** to correctly display **3 tabs**
2) **Comment out** history link
3) Remove **limit: 3** from Home tab to display all transactions
> Hide history tab

- src/css/variables.scss
- src/js/controllers/sidebar.js
1) Change wallet color in the side bar
2) Apply brand red to variables.scss
> Initial wallet color must be brand red

- src/js/services/chooseFeeTypeService.js
- src/js/services/configService.js
- src/js/services/fundingNodeService.js
> #243 save it in localstorage instead of conf.js??

- src/js/controllers/index.js
- src/js/controllers/splash.js
- src/js/services/changeWalletTypeService.js
> Issue-193: new implementation for change wallet type

- public/views/splash.html
- src/js/controllers/splash.js
> Issue-190 change the flow of new wallet registration

- public/views/preferencesGlobal.html
- src/js/controllers/preferencesGlobal.js
> #250 don't show Funding Node option if user has no bytes

- src/css/main.scss
> display full session log

- src/js/controllers/index.js
- src/js/controllers/preferencesDelete.js
- src/js/services/sharedService.js
…ch contains money
closes #257
> Issue-257: user should get a warning when trying to delete wallet which contains money

- src/js/controllers/correspondentDevices.js
> fixed pair device page in android

- src/js/controllers/index.js
- src/js/services/correspondentListService.js
- src/js/services/faucetService.js
> Issue-251: automatically pear wallet with faucet

- src/js/services/correspondentListService.js
> 274 feature

- src/js/controllers/index.js
- src/js/controllers/preferencesGlobal.js
- src/js/services/changeWalletTypeService.js
> Issue-262: Wallet not found error

- public/views/correspondentDevice.html
- src/js/controllers/correspondentDevice.js
- src/js/controllers/index.js
- src/js/services/connectionService.js
> Issue-272 Offline messages problems in chatbot (first solution)

- src/js/controllers/index.js
- src/js/services/faucetService.js
- src/js/services/fundingNodeService.js
> Issue-285 paired devices list blinking on full wallet

- public/views/preferencesGlobal.html
- src/js/controllers/index.js
> removes push notification slider

- cordova/config.xml
> loading spinner 

- .package.json
- Gruntfile.js
- bower.json
- public/index.html
- src/js/app.js
- src/js/controllers/index.js
- src/js/controllers/walletHome.js
- src/js/services/go.js
- test/karma.conf.js
> integrates sentry error reporting tool

- public/views/disclaimer.html
- public/views/splash.html
- src/css/main.scss
- src/js/controllers/splash.js
> Issue-299: change term and conditions

- public/views/splash.html
- src/css/main.scss
> Issue-309: change wallet type names on creation

- public/views/preferencesGlobal.html
- src/js/controllers/preferencesGlobal.js
- src/js/services/chooseFeeTypeService.js
> Issue-321: CHOOSE HOW TO PAY FEE issue

- public/views/correspondentDevice.html
- src/js/controllers/index.js
> Issue-322: Chatbot buttons have same colours as  additional wallet

- src/js/controllers/index.js
> Issue-332: bring back history page

- cordova/config.xml
- public/views/walletHome.html
- src/css/main.scss
> fixes header problem, and share screen visibility on android

- public/views/includes/password.html
> #362 fixed password buttons

- cordova/android/android.css
- cordova/build.sh
- environments.json
- public/views/walletHome.html
- src/css/mobile.scss
> #358 add scroll to android

- src/js/services/dagcoinProtocolService.js
- src/js/services/discoveryService.js
> Issue-354: Error to switch to light wallet

- public/views/acceptCorrespondentInvitation.html
- public/views/inviteCorrespondentDevice.html
- src/js/services/backButtonService.js
> fixed backbutton error

- public/views/includes/password.html
- src/js/controllers/password.js
> #382 make password restriction

- .package.json
- environments.json
- src/js/app.js
- src/js/controllers/walletHome.js
- src/js/services/fundingExchangeClientService.js
- src/js/services/proofingService.js
> Forbidding to use the funding address with secondary wallets

- .eslintignore
- .gitignore
- .package.json
- Gruntfile.js
- Makefile
- cordova/build.sh
- devbuilds/prepare-dev.sh
- devbuilds/prepare-package.sh
- environments.json
- environments/constant-template.ejs
- environments/live.json
- environments/testnet.json
- public/index.html
- src/js/app.js
- src/js/controllers/correspondentDevices.js
- src/js/controllers/index.js
- src/js/controllers/walletHome.js
- src/js/services/configService.js
- src/js/services/discoveryService.js
- src/js/services/faucetService.js
* added grunt-ng-constant dependency which takes json files and converts it in js file.
* added environment files under environment directory 
* changed build files, because we have two types of grunt build 
closes #316
> Env variables implementation

- src/js/controllers/correspondentDevice.js
- src/js/controllers/index.js
- src/js/controllers/preferencesInformation.js
- src/js/controllers/walletHome.js
- src/js/directives/directives.js
- src/js/services/correspondentListService.js
- src/js/services/proofingService.js
- src/js/services/sharedService.js
- src/js/services/txFormatService.js
Env based variables task #316 caused this bug because DAGCOIN_ASSEt was missing in some places.
Closes #495 
PR fixes error about asset definition while sending transaction.
> Fixes for sending transaction bug

- src/js/controllers/preferencesAlias.js
- src/js/controllers/preferencesDeviceName.js
Fixed issue with wallet name and device name length limit. Added Javascript checks for older android versions. 
Closes #501 
Added watch for wallet alies and device name variables in controllers.
> Fixed length limit for older android versions

- environments/testnet.json
- src/js/controllers/walletHome.js
- src/js/services/correspondentListService.js
- src/js/services/fundingExchangeClientService.js
Implementation changes to take advantage of the improvements in the funding node implementation
Closes #451 
- [ x] My code follows the code style of this project.
> 451 feature

- .travis.yml
The scope of this PR is to integrate Coday and disable codecov.
Closes #287 
Codecov only provides test coverage. Codacy in this sense is more practical it reviews code and generates reports
> Codacy integration

- src/js/directives/validAddress.directive.js
> 513: Validate address field in send page

- src/js/directives/whenScrolled.directive.js
> #521: New messages are hidden on chat page on Windows

- public/views/inviteCorrespondentDevice.html
- src/js/controllers/inviteCorrespondentDevice.js
Updates qr code to the new one (the same that is used in the receive tab) in the paired devices tab on invite new device action.
Closes #527 
Qr codes in the app have the same look and feel.
> Updates qr code in paired devices tab

- public/views/preferencesAbout.html
- public/views/preferencesGlobal.html
- src/css/main.scss
- src/css/settings.scss
Changed settings page css and removed pointer cursor from the password. 
Closes #479 
Settings page was out of overall design, so I made it a bit better looking.
> Settings page fixes

- src/js/controllers/index.js
> #509: Unnecessary pop-up after made transaction with funding node

- public/views/backup.html
- src/js/controllers/backup.js
- src/js/controllers/recoveryFromSeed.js
fixes idiomatic space, which is omitted when the seed words are copied to the TextEdit
closes #524 
Bug fix
> fixes idiomatic space

- public/views/acceptCorrespondentInvitation.html
- public/views/add.html
- public/views/addCorrespondentDevice.html
- public/views/backup.html
- public/views/correspondentDevices.html
- public/views/disclaimer.html
- public/views/export.html
- public/views/import.html
- public/views/inviteCorrespondentDevice.html
- public/views/paymentUri.html
- public/views/preferences.html
- public/views/preferencesAbout.html
- public/views/preferencesAdvanced.html
- public/views/preferencesDeviceName.html
- public/views/preferencesInformation.html
- public/views/preferencesLogs.html
- public/views/recoveryFromSeed.html
- public/views/walletHome.html
- src/css/main.scss
- src/css/variables.scss
- src/js/controllers/backup.js
- src/js/controllers/walletHome.js
1) **Font-size** of each input is **reduced to 12px**
2) **QR-scanner** button is now located outside the tab and **is shown in the header** once $rootScope.tab is set to "send"
3) The color of the inputs' border is now depending on two classes: success - for green, error - for red (global styling)
4) **Check marks**, which were initial indicators of correct inputs' values **were removed**.
closes #398
> UI/UX changes inside Send tab.

- public/views/preferencesInformation.html
- src/js/controllers/index.js
- src/js/controllers/preferencesInformation.js
Fixes single address wallet switch and hides 'add new wallet address' button, when enabled
Closes #565
> #565 - fixes single address wallet switch

- .package.json
- environments.json
- package-lock.json
- public/views/correspondentDevices.html
- src/js/controllers/correspondentDevices.js
- src/js/services/correspondentListService.js
> #524: Order chat based on last conversation

- public/views/addCorrespondentDevice.html
- public/views/create.html
- public/views/includes/topbar.html
- src/js/controllers/correspondentDevice.js
- src/js/controllers/create.js
- src/js/directives/dagTabs/dagTabs.directive.js
- src/js/directives/dagTabs/dagTabs.template.html
> #425: navigation bug

- public/views/preferencesGlobal.html
- public/views/walletHome.html
- src/css/main.scss
- src/css/variables.scss
- src/js/controllers/backup.js
- src/js/controllers/index.js
This pr implements notification for wallet seed backup 
closes #578
> #578 - implements backup warning notification

- .travis.yml
- src/js/services/go.js
> the err message converted to 'incorrect dagcoin address'

- src/js/services/uxLanguage.js
Disables automatic language recognition and sets English as a default language
Closes #619 
Customer request
> #619 - disables automatic language recognition and sets English as a default language

- public/views/modals/customized-amount.html
- src/js/controllers/walletHome.js
Changes generated message to human-readable text while sharing custom amount address to external sources 
closes #624
> fixes text for sharing custom amount

- public/views/disclaimer.html
- src/css/main.scss
> #654: Unable to confirm in intro page

- public/views/walletHome.html
- src/js/controllers/walletHome.js
- src/js/directives/dagTransactionsTable/dagTransactionsTable.scss
Аixes triple incoming transaction record, when received from several addresses.
Closes #715
> #715 - fixes triple transaction record

- public/views/modals/customized-amount.html
- src/css/main.scss
> rotates share icon

- Makefile
- cordova/build.sh
Requires latest Cordova (8.0) to work
Closes #702
> #702 - fixes IOS build script

- src/js/controllers/contacts/contact/edit_contact/edit_contact.controller.js
- src/js/controllers/contacts/contact/edit_contact/edit_contact.template.html
- src/js/controllers/contacts/contact/new_contact/new_contact.template.html
> #725 - adds length limits to address book contact fields

- src/js/controllers/index.js
> #832 User sees amount on an extract in dags, not microdags

- src/js/controllers/contacts/contact/contact.contoller.js
- src/js/controllers/contacts/contact/contact.scss
- src/js/controllers/contacts/contact/contact.template.html
Added send button in address book contact
> #730 add send button in address book contact

- src/js/controllers/backup.js
If password is required then seed is visible only after password inserting
> #859 Wallet seed getting visible after password inserted

- app/routers/webRoutes.js
- app/splash/splashDeviceName.js
- app/splash/splashWalletType.js
- web/webpack.config.dev.js
Added splashDeviceName, splashWalletType pages
> Added splashDeviceName, splashWalletType pages

- test/nightwatch/src/pages/pairedDevices.ts
- test/nightwatch/src/tests/android_tests/androidPairedDevices.test.ts
paired device test fix and fun. added to paired device page
> paired devises test fix

- test/nightwatch/src/pages/navMenu.ts
- test/nightwatch/src/tests/android_tests/androidMenu.test.ts
- test/nightwatch/src/texts/menu.ts
- test/nightwatch/src/texts/sideMenu.ts
android menu test code length reduced
> android menu test rewrite

- test/nightwatch/src/tests/android_tests/androidPairedDevices.test.ts
added check to paired devices test
> added extra to paired devices test

- test/nightwatch/src/tests/android_tests/androidAddressBook.test.ts
added extra check to address book test
> added new check to address book test
